spring:
  h2:
    console:
      enabled: true
      path: /restaurant-db

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:restaurant-db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  thymeleaf:
    cache: false